begin;

create table if not exists public.signers (
    id bigint generated by default as identity primary key,
    name text not null check (char_length(name) between 1 and 200),
    sport text not null check (char_length(sport) between 1 and 120),
    team text check (team is null or char_length(team) between 1 and 120),
    success_rate text check (success_rate is null or char_length(success_rate) between 1 and 20),
    avg_response text check (avg_response is null or char_length(avg_response) between 1 and 120),
    tested_address text check (tested_address is null or char_length(tested_address) between 1 and 2000),
    created_at timestamptz not null default now()
);

create index if not exists signers_name_idx
    on public.signers (name);

alter table public.signers enable row level security;

drop policy if exists lc_signers_public_read on public.signers;
create policy lc_signers_public_read
    on public.signers for select
    to anon, authenticated
    using (true);

drop policy if exists lc_signers_authenticated_insert on public.signers;
create policy lc_signers_authenticated_insert
    on public.signers for insert
    to authenticated
    with check (auth.uid() is not null);

grant select on public.signers to anon, authenticated;
grant insert on public.signers to authenticated;

create table if not exists public.community_posts (
    id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users(id) on delete cascade,
    author_name text not null check (char_length(author_name) between 1 and 120),
    player_name text not null check (char_length(player_name) between 1 and 120),
    result text not null check (result in ('success', 'pending', 'no-response', 'returned')),
    days_to_response integer check (days_to_response between 0 and 3650),
    experience text not null check (char_length(experience) between 1 and 2000),
    created_at timestamptz not null default now()
);

create index if not exists community_posts_created_at_idx
    on public.community_posts (created_at desc);

alter table public.community_posts enable row level security;

drop policy if exists lc_community_posts_public_read on public.community_posts;
create policy lc_community_posts_public_read
    on public.community_posts for select
    to anon, authenticated
    using (true);

drop policy if exists lc_community_posts_owner_insert on public.community_posts;
create policy lc_community_posts_owner_insert
    on public.community_posts for insert
    to authenticated
    with check (auth.uid() = user_id);

grant select on public.community_posts to anon, authenticated;
grant insert on public.community_posts to authenticated;

notify pgrst, 'reload schema';

commit;
